{% set name = "pypulse" %}
{% set version = "0.1.2" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 4904d46557426625b374a9c87d96c31f0c25258c74696d944d2371ea30877b8b

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  host:
    - python >=3.8
    - pip
    - numpy >=1.16.3
    - matplotlib-base
    - astropy
    - scipy >=1.2.0
  run:
    - python >=3.8
    - numpy >=1.16.3
    - scipy >=1.2.0
    - matplotlib-base
    - astropy

test:
  imports:
    - pypulse
  requires:
    - pip
  commands:
    - pip check

about:
  home: https://github.com/mtlam/PyPulse
  summary: A python package for handling and analyzing PSRFITS files.
  license: BSD-3-Clause
  license_file: LICENSE.md

extra:
  recipe-maintainers:
    - AaronDJohnson
    - mtlam
    - JPGlaser
